import {
  CreateOrderDraftInput,
  ImportError,
  ImportKind,
  ParsedOrderDraft,
  TextExtractor
} from '../../lib/import-types';
import { buildImportSource } from './fileType';
import { extractHallorenItemsFromRawText, hardenHallorenImageItems } from './hallorenCatalog';
import { extractTextFromPdf } from './pdf';
import { extractTextFromImage } from './ocr';
import { parseOrderText } from './parser';

function buildDraftTitle(file: File, sourceKind: ImportKind) {
  const baseName = file.name.replace(/\.[^.]+$/, '').trim();
  const looksAutogenerated =
    /^whatsapp image/i.test(baseName) ||
    /^img[-_ ]/i.test(baseName) ||
    /^pxl[-_ ]/i.test(baseName) ||
    /^\d{10,}$/.test(baseName);

  if (sourceKind === 'image' && (looksAutogenerated || baseName.length > 28)) {
    const stamp = new Date(file.lastModified || Date.now());
    const dateText = stamp.toLocaleDateString('de-DE');
    const timeText = stamp.toLocaleTimeString('de-DE', {
      hour: '2-digit',
      minute: '2-digit'
    });
    return `Fotoauftrag ${dateText} ${timeText}`;
  }

  return baseName || 'Neuer Auftrag';
}

async function extractFromPdf(file: File, pdfExtractor?: TextExtractor) {
  const pdf = pdfExtractor ?? extractTextFromPdf;
  return await pdf(file);
}

async function extractFromImage(file: File, ocrExtractor?: TextExtractor) {
  const ocr = ocrExtractor ?? extractTextFromImage;
  return await ocr(file);
}

async function extractWithFallback(
  file: File,
  sourceKind: ImportKind,
  pdfExtractor?: TextExtractor,
  ocrExtractor?: TextExtractor
) {
  if (sourceKind === 'image') {
    return await extractFromImage(file, ocrExtractor);
  }

  if (sourceKind === 'pdf') {
    return await extractFromPdf(file, pdfExtractor);
  }

  try {
    const pdfResult = await extractFromPdf(file, pdfExtractor);
    if (pdfResult.text.trim()) {
      return pdfResult;
    }
    return await extractFromImage(file, ocrExtractor);
  } catch (pdfError) {
    try {
      return await extractFromImage(file, ocrExtractor);
    } catch {
      throw pdfError;
    }
  }
}

export async function createOrderDraftFromImport(input: CreateOrderDraftInput): Promise<ParsedOrderDraft> {
  const { file } = input;
  const source = await buildImportSource(file);
  const extraction = input.text
    ? { text: input.text }
    : await extractWithFallback(file, source.kind, input.pdfExtractor, input.ocrExtractor);

  const rawText = extraction.text.trim();
  if (!rawText) {
    throw new ImportError('EMPTY_INPUT', 'Aus der Datei konnte kein Text gelesen werden.');
  }

  const parsed = parseOrderText(rawText, buildDraftTitle(file, source.kind));
  const hallorenItems = source.kind === 'image' ? extractHallorenItemsFromRawText(rawText) : [];
  const hardenedItems =
    source.kind === 'image'
      ? hallorenItems.length >= 3
        ? hallorenItems
        : hardenHallorenImageItems(parsed.items)
      : parsed.items;
  return {
    ...parsed,
    items: hardenedItems.length > 0 ? hardenedItems : parsed.items,
    source,
    rawText,
    warnings: [...parsed.warnings, ...(extraction.warnings ?? [])]
  };
}
